# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Dr. Lauriane Ribas-Deulofeu
email: lauriane.ribas@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Welcome to Dr. L Ribas-Deulofeu's website. Discover my research on coral reef ecosystems.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Company Information
company_name: Institute of Oceanography, National Taiwan University
address_line: IONTU R120, No. 1, Section 4, Roosevelt Rd, Da’an District, Taipei City, 106 (Taiwan)
#telephone_number: NA
#fax_number: NA
company_email: lauriane.ribas@gmail.com
google_map: https://www.google.com/maps/embed?pb=!1m14!1m8!1m3!1d14461.507790783593!2d121.5372973!3d25.0212787!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x0%3A0xbd89373059c37211!2sInstitute%20of%20Oceanography%2C%20National%20Taiwan%20University!5e0!3m2!1sen!2stw!4v1660877933220!5m2!1sen!2stw

# Social Link
#facebook_link: http://www.facebook.com
twitter_link: "https://twitter.com/laurianeribas"
webofscience_link: "https://www.webofscience.com/wos/author/record/AAC-2793-2022"
orcid_link: "https://orcid.org/0000-0001-9005-5547" 
researchgate_link: "https://www.researchgate.net/profile/Lauriane-Ribas-Deulofeu"
linkedin_link: "https://www.linkedin.com/in/lauriane-ribas-deulofeu/"
googlescholar_link: "https://scholar.google.com/citations?user=DTU8D8QAAAAJ&hl=en"

# Build settings
markdown: kramdown
plugins:
  - jekyll-feed

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
